# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madness', models.IntegerField(default=1)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('exclusive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_exclusive', to='tournament.RegionData')),
                ('ff_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_ff_match', to='tournament.RegionData')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('seed', models.IntegerField()),
                ('power', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.RegionData')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upsets', models.IntegerField(default=0)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Options')),
                ('runnerup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Year'),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Year'),
        ),
        migrations.AddField(
            model_name='regiondata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Year'),
        ),
        migrations.AddField(
            model_name='region',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='options',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='options',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='options',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Year'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Round'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semis', to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Team'),
        ),
    ]
