# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_options_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Year'),
        ),
    ]
