# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_options_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='madness',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
